sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker-compose build
  - docker-compose run tests
  - docker-compose run fib-calculator